### ISSUE TITLE
请问可以合成为一个文件吗

### ISSUE THREAD

**Issue by donggelaile** [zhangxigithub/AutomaticCoder#1]
您好，您写的这个生成器很大程度的简化了开发过程。确实已经很不错了。但是还是提出一点建议，就是希望可以只生成一个.h和.m文件，其中.h中声明多个类，.m中完成每个类的初始化方法。最终只有最外边的类暴露初始化方法。这样的话可以减少文件个数，一个文件就是一个大的Model。也避免了其中一些小Model 重名的问题。谢谢。

**Comment by zhangxigithub** [comment]
确实合理，把model都放在一起，不过这个很老了。。比较不大想动这个项目了~.~ ，以后有时间想改成生成swift的类。
